name = "logic"
defaultTargets = ["Logic"]

[[lean_lib]]
name = "Logic"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.9.0"

[[require]]
name = "extra"
git = "https://github.com/fgdorais/extra4"
rev = "stable"
