import Logic.Basic
import Logic.Cast.Basic
import Logic.Equiv.Basic
import Logic.Equiv.Fun
import Logic.Equiv.List
import Logic.Equiv.Option
import Logic.Equiv.Prod
import Logic.Equiv.Quotient
import Logic.Equiv.Sigma
import Logic.Equiv.Subtype
import Logic.Equiv.Sum
import Logic.Predicate.Classes
import Logic.Proposition.Classes
import Logic.Proposition.Lemmas
import Logic.Proposition.Tactics
